// import "./globals.css";
"use client";
import { Grid } from "@mui/material";
import { Inter } from "next/font/google";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>{children}</div>
          <div></div>
          <div></div>
        </div>
        <Grid container spacing={3}>
          <Grid item xs></Grid>
          <Grid item xs={6}></Grid>
          <Grid item xs></Grid>
        </Grid>
      </body>
    </html>
  );
}
